import { defineConfig } from "@/lib/config";

// Private clone configuration - generated by setup script
const useCloneBranding = true;

export default defineConfig({
  // Branding - your organization's identity
  branding: {
    name: "kelly ops library",
    logo: "/logo.svg",
    logoDark: "/logo.svg",
    favicon: "/logo.svg",
    description: "AI-powered prompt and workflow library for lead generation,outreach,sales,and business operations.",
  },

  // Theme - design system configuration
  theme: {
    radius: "md",
    variant: "default",
    density: "default",
    colors: {
      primary: "#2563EB",
    },
  },

  // Authentication plugins
  auth: {
    providers: ["credentials"],
    allowRegistration: false,
  },

  // Internationalization
  i18n: {
    locales: ["en"],
    defaultLocale: "en",
  },

  // Features
  features: {
    privatePrompts: true,
    changeRequests: true,
    categories: true,
    tags: true,
    comments: true,
    aiSearch: false,
    aiGeneration: false,
    mcp: false,
  },

  // Homepage customization (clone branding mode)
  homepage: {
    useCloneBranding,
    achievements: {
      enabled: false, // Disabled for private clones
    },
    sponsors: {
      enabled: false,
      items: [],
    },
  },
});
